//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FightFleet.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=localhost\\SQLEXPRESS;Initial Catalog=FightFleet;User ID=FightFleet;Pa" +
            "ssword=comp412")]
        public string FightFleetConnectionString {
            get {
                return ((string)(this["FightFleetConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=7abe2269-e12c-4076-9ab9-a0f500139bf1.sqlserver.sequelizer.com;Initial" +
            " Catalog=db7abe2269e12c40769ab9a0f500139bf1;User ID=ufosakngychouvjv;Password=cJ" +
            "p4JzdgZZYeVhAocmUdt68SrXf42LrkcdPzvyzwiB2jGBAYLeFLetDfJEKTuino")]
        public string db7abe2269e12c40769ab9a0f500139bf1ConnectionString {
            get {
                return ((string)(this["db7abe2269e12c40769ab9a0f500139bf1ConnectionString"]));
            }
        }
    }
}
